version: "3"
services:
  lxsts:
    container_name: lxsts
    image: ghcr.io/effree/lxsts:latest
    ports:
      - '5123:5000'
    volumes:
      - ./data:/app/data
    environment:
      - LOGIN_USERNAME=admin
      - LOGIN_PASSWORD=changeme
      - SECRET_KEY=change-this-to-a-random-secret-key
    restart: unless-stopped
